spring.application.name=orders-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/db_orders
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=orders-service
spring.kafka.consumer.auto-offset-reset=earliest